config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resources :people
  resources :articles
  get 'search', to: 'search#search'
  get 'quick_search', to: 'search#quick_search'
  get 'suggest/:term' => 'search#suggest'

  get 'name/search', to: 'search_names#search', as: 'search_names'
  get 'name/misspellings/:name_term' => 'search_names#misspellings'
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def quick_search
    @articles = if params[:query].blank?
      []
    else
      Article.search( params[:query] )
    end
  end

  def search
    if params[:term].nil?
      @articles = []
    else
      @articles = Article.quick_search params[:term]
    end
  end

  def suggest
    result = Article.auto_complete(params[:term]).map do |article|
      {title: article["_source"]["title"], value: article["_source"]["id"]}
    end
    render json: result
  end

  def misspellings

  end
end

app/helpers/search_helper.rb
module SearchHelper
  def autosuggest_aggregate(response, fields, query)
    # Stores unique words and their autocorrect suggestions
    words = { }

    # Iterate over fields
    fields.each do |field|
      # Iterate over query words
      response.send(field).to_a.each do |word|
        # If any options are available
        if word.options.length > 0
          # Append word if it doesn't already exist
          new_word = false
          unless words.include? word.text
            words[word.text] = { text: '', score: nil, freq: nil }
            new_word = true
          end
          word.options.each do |option|
            if new_word or words[word.text][:score] * words[word.text][:freq] < option[:score] * option[:freq]
              words[word.text][:text] = option[:text]
              words[word.text][:score] = option[:score]
              words[word.text][:freq] = option[:freq]
            end
          end
        end
      end
    end

    new_query = query.dup

    # Generate a new string based on the high score suggestions
    words.each do |word, suggestion|
      if suggestion[:score] > 0.65
        new_query[word] = suggestion[:text]
      end
    end

    # Return the new query or false if there were no modifications
    return new_query unless new_query == query
    false
  end
end

app/views/search/quick_search.slim
h1 ES Search Demo

= form_tag quick_search_path, method: :get
  = text_field_tag :query, params[:query]
  = button_tag 'Search'

- if @articles
  h2
    | Search
    small
      = ' (' + pluralize(@articles.count, 'result') + ')'
      | &nbsp;
      - if @articles.respond_to? :took
        small = 'performed in ' + ( @articles.took.to_f / 1000 ).to_s + ' seconds'

  - if @articles.respond_to? :response and (suggestion = autosuggest_aggregate(@articles.response.suggest, [:title, :text], params[:query]))
    p
      | Search instead for:
      = link_to suggestion, search_path( query: suggestion )

  - @articles.each do |page|
    article
      h3 = page.title
      - if page.respond_to? :highlight
        p = raw page.highlight.body.to_a.join(' ')
      - else
        p = raw truncate(page.body, length: 300)

  - if @articles.count == 0
    p No articles found
- else
  p Enter your search term using the form above

app/views/search/search.html.erb
<%= form_for :term, url: search_path, method: :get do |form| %>
  <p>
    <%= text_field_tag :term, params[:term] %>
    <%= submit_tag "Search", name: nil %>
  </p>
<% end %>

<h1>Search Results of <%= params[:term] %></h1>

<% if @articles %>
  <ul class="search_results">
    <% @articles.each do |article| %>
      <li>
        <h3>
          <%= link_to article.try(:highlight).try(:title) ?
              article.highlight.title[0].html_safe : article.title,
              controller: "articles", action: "show", id: article._id %>
        </h3>
        <% if article.try(:highlight).try(:text) %>
          <% article.highlight.text.each do |snippet| %>
          <p><%= snippet.html_safe %>...</p>
        <% end %>
      <% end %>
    </li>
  <% end %>
</ul>
<% else %>
  <p>Your search did not match any documents.</p>
<% end %>