config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resources :people
  resources :articles
  get 'search', to: 'search#search'
  get 'quick_search', to: 'search#quick_search'
  get 'suggest/:term' => 'search#suggest'

  get 'name/search', to: 'search_names#search', as: 'search_names'
  get 'name/misspellings/:name_term' => 'search_names#misspellings'
end

app/controllers/search_names_controller.rb
class SearchNamesController < ApplicationController
  def search
    if params[:name_term].nil?
      @people = []
    else
      @people = Person.search params[:name_term]
    end
  end

  def misspellings
    result = Person.auto_complete(params[:name_term]).map do |person|
      {name: person["_source"]["name"], value: person["_source"]["id"]}
    end
    render json: result
  end
end

app/views/search_names/search.html.erb
<%= form_for :term, url: search_names_path, method: :get do |form| %>
  <p>
    <%= text_field_tag :name_term, params[:name_term] %>
    <%= submit_tag "Search", name: nil %>
  </p>
<% end %>

<h1>Search Results of <%= params[:name_term] %></h1>

<% if @people %>
  <ul class="search_results">
    <% @people.each do |person| %>
      <li>
        <h3>
          <%= link_to person.try(:highlight).try(:name) ?
              person.highlight.name[0].html_safe : person.name,
              controller: "people", action: "show", id: person._id %>
        </h3>
        <% if person.try(:highlight).try(:first_name) %>
          <% person.highlight.first_name.each do |snippet| %>
            <p><%= snippet.html_safe %>...</p>
          <% end %>
        <% end %>

        <% if person.try(:highlight).try(:last_name) %>
          <% person.highlight.last_name.each do |snippet| %>
            <p><%= snippet.html_safe %>...</p>
          <% end %>
        <% end %>
    </li>
  <% end %>
</ul>
<% else %>
  <p>Your search did not match any documents.</p>
<% end %>